### ISSUE TITLE
Error during generation of .lg file for certain projects

### ISSUE THREAD

**Issue by manish-95** [Botmock/botmock-botframework-export#23]
**Issue Overview**
When I run the script to generate the .lu and .lg files for certain Projects in BotMock, the .lu file is generated but during .lg file generation , I get an error as follows:
`
TypeError: Cannot destructure property 'name' of 'undefined' or 'null'.
    at C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:177:17
    at Array.map (<anonymous>)
    at C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:176:44
    at Array.reduce (<anonymous>)
    at FileWriter.findRequiredSlotsForConnectedIntents (C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:174:8)
    at C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:205:38
    at Array.reduce (<anonymous>)
    at FileWriter.writeLGFile (C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:202:10)
    at FileWriter.write (C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\lib\file.ts:225:16)
    at main (C:\Users\ManishSridhar\Desktop\Botmock\botmock-botframework-export\index.ts:68:3)
`

**Steps To Reproduce**
1. Set the values in .env file
2. Run the script with **npm start**

**Expected Behavior**
Given a valid board and project id, the .lg file is generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/29098159/72340815-d7de2e00-36ee-11ea-8a39-4815dd879c1a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.13.1
 - NPM Version: 6.12.0

**Comment by obaid** [comment]
Thanks for reporting the issue @manish-95. Our team will work on pushing a fix for this shortly.
